name: Upload Python Package

on:
  release:
    types: ["published"]

  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to PyPi
    environment: release
    permissions:
      id-token: write
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build package
        shell: bash
        run: |
          python3 -m build

      - name: 🚀 Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
